apiVersion: apps/v1
kind: Deployment
metadata:
  name: client-react-with-https
  labels:
    app: client-react-with-https
spec:
  replicas: 1
  selector:
    matchLabels:
      app: client-react-with-https
  template:
    metadata:
      labels:
        app: client-react-with-https
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        ports:
          - containerPort: 443
        volumeMounts:
          - name: tls-secret
            mountPath: /etc/nginx/tls
            readOnly: true
          - name: nginx-config
            mountPath: /etc/nginx/nginx.conf
            subPath: nginx.conf
      volumes:
        - name: tls-secret
          secret:
            secretName: {{ .Values.tlsSecretName }}
        - name: nginx-config
          configMap:
            name: nginx-config
