apiVersion: v1
kind: Service
metadata:
  name: client-react-service-https
  annotations:
    "helm.sh/resource-policy": keep
spec:
  selector:
    app: client-react-with-https
  type: NodePort
  ports:
    - name: https
      protocol: TCP
      port: 443
      targetPort: 443
      nodePort: {{ .Values.service.nodePort }}
